faction creation cost: 3000.0
influence per player: 50.0
default faction name: Capitol Faction
Claim Influence Cost: 1.0
deathCost: 3.0
Modify mob xp drops: true
#Warstuff
warDuration (h): 24
warCost: 10.0
#WarpStuff
warpCost: 0.01 #Cost per block for a warp
warpCreationCost: 100 #Cost to create a warp
warpScale: 1.2 #Scale factor: cost(#warps)=warpCreationCost*(#warps)^warpScale. Set to 0 to disable scaling
bindBeaconToFaction: true #do beacons only effect the player 
#loans
Currency Symbol: Ƒ #currency symbol used by plugin.
default interest: 0.01 #default is 1%/hour
default loan length: 100 #default is 100 hours
Banner Price: 10