main: ZenaCraft.App
name: ZenaFactions
version: 0.1.4
api-version: 1.16
depend: ["Vault"]
commands:
  listFactions:
    description: lists the current server factions
    usage: /<command>
  createFaction:
    description: creates a new faction
    usage: /<command> [faction name]
  saveDB:
    description: saves databases
    usage: /<command>
  factionBalance:
    description: returns faction balance
    usage: /<command>
  factionInfluence:
    description: returns faction influence
    usage: </command>
  setPrefix:
    description: changes prefix and color. Allowed colors are red, orange, purple, blue, and green
    usage: /<command> [prefix] [color]