main: ZenaCraft.App
name: ZenaFactions
version: 0.1.12.1
api-version: 1.16
depend: ["Vault", "dynmap", "GriefPrevention"]
commands:
  listFactions:
    description: lists the current server factions
    usage: /<command>
  createFaction:
    description: creates a new faction
    usage: /<command> [faction name]
  saveDB:
    description: saves databases
    usage: /<command>
  factionBalance:
    description: returns faction balance
    usage: /<command>
  factionInfluence:
    description: returns faction influence
    usage: </command>
  listLoadedFQChunks:
    description: lists loaded FQC's
    usage: /<command>
  claimChunk:
    description: claims chunk for your faction
    usage: /<command> [radius]
  toggleAutoClaim:
    description: toggles autoclaiming of unclaimed chunks for your faction
    usage: /<command> [autoclaiming radius]
  listMembers:
    description: lists faction members
    usage: /<command>
  setInfluence:
    description: sets faction influence
    usage: /<command> [faction] [influence]
  joinFaction:
    description: leave your current faction and join a new one in the lowest rank
    usage: /<command> [faction]
  promote:
    description: promotes the specified player one rank
    usage: /<command> [player to be promoted]
  demote:
    description: demotes the specified player one rank
    usage: /<command> [player to be demoted]
  changeRankNames: 
    description: changes the names of the ranks in your faction
    usage: </command> [Highest rank] [Middle rank] [lowest rank]
  declarewar:
    description: declares war on the target faction. Current location will automatically be added to the warzone
    usage: </command> [target faction]
  warscore:
    description: gets warscore of current war
    usage: </command>
  listwars:
    description: lists current wars
    usage: /<command>
  addToWarZone:
    description: adds current location to war demands
    usage: /<command>
  createWarp:
    description: creates warp to current location
    usage: /<command> [warp name]
  warp:
    description: warps you to your destination
    usage: /<command> [warp name]
  listwarps:
    description:  lists avaliable warps
    usage: /<command>
  changefactioncolour:
    description: changes colour of your faction. All default mc colour names are allowed.
    usage: /<command> [colour]
  changefactionname:
    description: changes name of your faction.
    usage: /<command> [name]
  setwarptax:
    description: changes the tax (in %) that your faction collects over the cost of the specified warp.
    usage: /<command> [warp name] [tax in %]
  setwarprank:
    description: changes the minimum rank required to use this warp.
    usage: /<command> [warp name] [rank name]
  createloan:
    description: creates a loan. Everyone may accept this loan, not just members of your faction!
    usage: /<command> [amount to loan]
  listloans:
    description: lists avaliable loans
    usage: </command>
  takeloan:
    description: takes out loan from a faction. Be sure to pay it back!
    usage: </command> [faction] [loan number]
  payloan:
    description: pays specified loan from specified faction. If you don't have enough money to pay the loan, a new one will be created.
    usage: </command> [faction] [loan number]