main: ZenaCraft.App
name: ZenaFactions
version: 0.1.10
api-version: 1.16
depend: ["Vault", "dynmap", "GriefPrevention"]
commands:
  listFactions:
    description: lists the current server factions
    usage: /<command>
  createFaction:
    description: creates a new faction
    usage: /<command> [faction name]
  saveDB:
    description: saves databases
    usage: /<command>
  factionBalance:
    description: returns faction balance
    usage: /<command>
  factionInfluence:
    description: returns faction influence
    usage: </command>
  setPrefix:
    description: changes prefix and color. Allowed colors are red, orange, purple, blue, and green
    usage: /<command> [prefix] [color]
  listLoadedFQChunks:
    description: lists loaded FQC's
    usage: /<command>
  claimChunk:
    description: claims chunk for your faction
    usage: /<command> [radius]
  toggleAutoClaim:
    description: toggles autoclaiming of unclaimed chunks for your faction
    usage: /<command> [autoclaiming radius]
  listMembers:
    description: lists faction members
    usage: /<command>
  setInfluence:
    description: sets faction influence
    usage: /<command> [faction] [influence]
  joinFaction:
    description: leave your current faction and join a new one in the lowest rank
    usage: /<command> [faction]
  promote:
    description: promotes the specified player one rank
    usage: /<command> [player to be promoted]
  demote:
    description: demotes the specified player one rank
    usage: /<command> [player to be demoted]
  changeRankNames: 
    description: changes the names of the ranks in your faction
    usage: </command> [Highest rank] [Middle rank] [lowest rank]
  declarewar:
    description: declares war on the target faction. Current location will automatically be added to the warzone
    usage: </command> [target faction]
  warscore:
    description: gets warscore of current war
    usage: </command>
  listwars:
    description: lists current wars
    usage: /<command>